#!/bin/bash
clear

alert_count=$(sudo mysql -u pi -bs <<<"select count(*) from VATS.COMMUNITY_ALERTS;")
echo

#show a list of all community alerts that haven't been archived
echo "Current Alerts: $alert_count"
echo
i=0
while read name subject
do
    echo "Alert $(( i++ )):" 
    echo "  Name: $name"
    echo "  Subject: $subject"
    echo
done < <(sudo mysql -u pi -Bs <<<"select MemberName,Subject from VATS.COMMUNITY_ALERTS;")

#give the admin the option to select an alert for details

while [ true ];
do
    echo "Select an alert to see details, or enter 'q' to return to the admin menu"
    read select_alert

    #quit
    re='^[0-9]+$'
    if ! [[ $select_alert =~ $re ]] ; then
        #quit
        if [[ $select_alert == *['!'q]* ]] || [[ $select_alert == *['!'Q]* ]]
        then
            exit
        fi
    fi
    if [ $select_alert -lt $alert_count ]
    then
        read name date date_time subject details < <(sudo mysql -u pi -bs <<<"select * from VATS.COMMUNITY_ALERTS LIMIT $select_alert,1")
        echo
        echo $name
        echo $date $date_time
        echo $subject
        cowsay $details
        echo
    else
        echo "error: no such alert"
    fi

done

exit
