#!/bin/bash
#get the directory where the script was executed
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

clear
echo "Welcome back, admin: "
echo
PS3='What do you want to do? (Enter 6 for menu)  '
options=("Log Inventory" "Log rate of consumption" "View VATS suggestions" 
        "View community alerts" "View Inventory" "Menu" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Log Inventory")
            echo "you chose choice 1"
            ;;
        "Log rate of consumption")
            echo "you chose choice 2"
            ;;
        "View VATS suggestions")
            echo "you chose choice 3"
            ;;
        "View community alerts")
            "$DIR"/admin_community_alerts
            ;;    
        "View Inventory")

            ;;
        "Menu")
            echo "1) Log Inventory	    5) View Inventory"
            echo "2) Log rate of consumption  6) Menu"
            echo "3) View VATS suggestions    7) Quit"
            echo "4) View community alerts"
            ;;
        "Quit")
            break
            ;;
        *) echo invalid option;;
    esac
done