#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

while [ true ];
do
    echo "Enter the number of the item you wish to log or:"
    echo "a: add a new item type"
    echo "p: print the inventory list"
    echo "q: return to the admin menu"
    read item_index

    #quit
    re='^[0-9]+$'
    if ! [[ $item_index =~ $re ]] ; then
        if [[ $item_index == *['!'a]* ]] || [[ $item_index == *['!'A]* ]]; then
            echo "Give the name of the item:"
            read new_item_name
            echo "Give the existing quantity of the item:"
            read new_item_quantity
            echo "Give the approximate consumption rate of the item (in terms of quantity per day)"
            read new_item_rate
            #get the TTD of the item
            new_item_TTD=$(echo "$new_item_quantity $new_item_rate" | java -cp $DIR/../backend calcTTD)
            sudo mysql -u pi <<< "INSERT INTO VATS.INVENTORY VALUES (\"$new_item_name\",$new_item_quantity,$new_item_rate,\"$new_item_TTD\",\"\", now());"
            continue
        elif [[ $item_index == *['!'q]* ]] || [[ $item_index == *['!'Q]* ]]; then
            echo
            exit
        elif [[ $item_index == *['!'p]* ]] || [[ $item_index == *['!'P]* ]]; then
            #get the directory where the script was executed
            echo
            "$DIR"/view_inventory
            continue
        fi
    fi

    item_count=$(sudo mysql -u pi -bs <<<"select count(*) from VATS.INVENTORY;")

    if [ $item_index -lt $item_count ]
    then
        read name roc < <(sudo mysql -u pi -bs <<<"select Item,RateOfConsumption from VATS.INVENTORY LIMIT $item_index,1")
        echo
        echo "Enter the new quantity of " $name
        read quantity
        if [ $quantity -gt 0 ]; then
            new_TTD=$(echo "$quantity $roc" | java -cp $DIR/../backend calcTTD)
            sudo mysql -u pi <<< "UPDATE VATS.INVENTORY SET Quantity=$quantity,TimeToDepletion=\"$new_TTD\" WHERE Item=\"$name\";"
            echo "$name quantity updated"
        else
            echo "error: cannot have negative quantity"
        fi
    else
        echo "error: item does not exist"
    fi

done
