#!/bin/bash

echo "Current Inventory Items: "
echo
i=0
while read item quantity TDD
do
    echo "$(( i++ ))  $item"
    echo "      Quantity: $quantity"
    echo "      Time to Depletion: $TDD"
    echo
done < <(sudo mysql -u root -Bs <<<"select Item,Quantity,TimeToDepletion from VATS.INVENTORY;")
exit