#!/bin/bash

echo "Current Inventory Items: "
echo
i=0
while read item quantity roc TDD
do
    echo "$(( i++ ))  $item"
    echo "      Quantity: $quantity"
    echo "      Rate of consumption: $roc"
    echo "      Time to Depletion: $TDD"
    echo
done < <(sudo mysql -u pi -Bs <<<"select Item,Quantity,RateOfConsumption,TimeToDepletion from VATS.INVENTORY;")
exit
